import React from "react"

/* Import Global Components */
import InterviewAnswer from "~components/interviewAnswer/interviewAnswer"
import InterviewQuestion from "~components/interviewQuestion/interviewQuestion"

const EnglishContent = () => (
  <div>
    <p>
      Interview by Maria Camila Montalvo Senior with SHE Collective, Se habla
      español, formed by Noelia Lecue Francia, María Alejandra Sáenz García,
      Andrea Valencia Aranda, and Natalia Viera Salgado.
    </p>
    <p>
      The curatorial collective Se habla español, comprised of Noelia Lecue
      Francia, María Alejandra Sáenz Garcia, Andrea Valencia Aranda and Natalia
      Viera Salgado, invites artists, designers, writers, photographers and
      curators around the world to submit a work, poem, image or short video
      (you can use your cell phone camera!) to share a message of SOLIDARITY in
      these uncertain times. The purpose of the images, which we will be sharing
      with our networks, will be to reimagine the future after the pandemic.
      Send your message along with a short paragraph and the image credit to
      colectivosehablaespanol@gmail.com. Let's spread SOLIDARITY.
    </p>
    <InterviewQuestion interviewer="Maria Camila Montalvo Senior (MCMS)">
      In the present moment, I have seen many things in my daily life that I
      have not seen before. It is as if from one moment to the next, the
      dimension of time has been amplified and I am able to sit and contemplate
      everything around me in slow motion. For example, I discovered that my
      African neighbors who live in community, practice rituals in their
      backyard at night. I sit and listen to their music and I think they dance;
      I can barely see their shadows or silhouettes because it is so dark. Then
      in the morning, I see trunks nailed to the ground and tied together with
      red ribbon. A mandala of stones surrounds them. I look for African music
      on Spotify and listen to it all day. It is as if through observation, I
      have become part of the ritual and of that community, which opened up
      another world to me, another dimension. I see the same thing in Caro
      Dalfó's piece for SOLIDARITY. She says, "It is short, simple and mundane .
      . . My neighbor, whom I do not know, practices his saxophone and it makes
      my day. A small moment of happiness.” In both these cases, I find gestures
      of solidarity. It is a solidarity generated by an internal cohesion that
      comes from the observation of what exists at this moment and with those
      particular sensations. Both cases bring a degree of fantasy to the
      enchantment. But I also believe that the gesture of my contemplation or
      that of Caro is key within this solidarity. Everyone is there for me,
      everyone is being supportive; those who observe and those who listen. In
      this regard, I would like you to define the concept of solidarity more
      precisely in relation to the work you have received and to this moment in
      time. For you, what is solidarity?
    </InterviewQuestion>
    <InterviewAnswer subject="Se habla español (SHE):">
      Solidarity is a concept that goes beyond this particular public health
      emergency. Since the beginning of Se habla español, the collective has had
      a spirit of collaboration and mutual support that has been essential for
      the creation of our projects. Solidarity is a way of relating to others,
      understanding that we are a network and that if one part of the network is
      vulnerable, then we are all vulnerable. On the contrary, when we support
      each other and strengthen the network, we all become stronger.{" "}
    </InterviewAnswer>
    <InterviewAnswer>
      At this moment, solidarity is a way of creating bridges to connect us in
      different ways and on different levels. The SOLIDARITY HAS NO BORDERS
      initiative was born from a feeling of empathy and affection towards each
      other, of extending a hand in a difficult moment of social distancing to
      continue strengthening our community. Now, solidarity demands from us more
      than a gesture, it demands that we contribute and create a platform for
      those who wish to express themselves. Our proposal was also born out of a
      need to amplify messages of empathy in a time when collective fear and
      panic have spread in an alarming way.
    </InterviewAnswer>
    <InterviewAnswer>
      The poet Arundhati Roy recently said, "Historically, pandemics have forced
      humans to break with the past and imagine their world anew. This one is no
      different. It is a portal, a gateway between one world and the next." For
      us, the importance of this project is related to the power in the creation
      of that world to come.
    </InterviewAnswer>
  </div>
)

export default EnglishContent
